name: maya-unit-testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  maya:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
       include:
         - maya: "2017"
         - maya: "2018"
         - maya: "2019"
         - maya: "2020"
         - maya: "2022"

    container: mottosso/maya:${{ matrix.maya }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Testing
        run: mayapy -m mayaunittest discover tests -v --pattern "test_*.py"
